version: '3.8'

services:
  spring-boot-app:
    image: eproduits:latest
    build:
      context: src
      dockerfile: Dockerfile
      args:
        JAR_FILE: target/GestionProduitsJ2EE-0.0.1-SNAPSHOT.jar
    ports:
      - "8086:8086"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-container:3306/produits?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 2704
    depends_on:
      - mysql-container

  mysql-container:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 2704
      MYSQL_DATABASE: produits
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: mysql-container

volumes:
  mysql_data: